---
- name: Deploy to K8s Cluster 
  hosts: all
  become: true
tasks:
  - name: Deploy Frontend
    shell: |
      kubectl apply -f frontend.yaml
  
  - name: Deploy Backend
    shell: | 
      kubectl apply -f backend.yaml