apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumia-frontend-api-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jumia-frontend-api
  template:
    metadata:
      labels:
        app: jumia-frontend-api
    spec:
      containers:
      - name: jumia-frontend-api
        image: dockub.coralpay.com/frontend:#{image-tag}#
        resources:
          limits:
            memory: "300Mi"
            cpu: "280m"        
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
          - name: PORT
            value: "8081"
      imagePullSecrets:
        - name: docker-cred
---

apiVersion: v1
kind: Service
metadata:
  name: jumia-frontend-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jumia-frontend-api
  ports:
  - port: 8081
    targetPort: 8081